export const SORTING_CREATE_TIME_ASCENDING = 'SORTING_CREATE_TIME_ASCENDING';
export const SORTING_CREATE_TIME_DESCENDING = 'SORTING_CREATE_TIME_DESCENDING';
export const SORTING_TITLE_ASCENDING = 'SORTING_TITLE_ASCENDING';
export const SORTING_TITLE_DESCENDING = 'SORTING_TITLE_DESCENDING';
