export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const NOTIFICATION_WARNING = 'NOTIFICATION_WARNING';
export const NOTIFICATION_INFORMATION = 'NOTIFICATION_INFORMATION';
export const NOTIFICATION_DISPLAY_TIME = 10000;
