module.exports = {
  PASSWORD_HASH_ALGORITHM_PARAMETER_SEPARATOR: ':',
  PASSWORD_HASH_ALGORITHM_PBKDF2: 'pbkdf2',
  PASSWORD_HASH_ALGORITHM_PBKDF2_DIGEST_METHOD: 'sha512',
  PASSWORD_HASH_ALGORITHM_PBKDF2_SALT_BYTE_SIZE: 64,
  PASSWORD_HASH_ALGORITHM_PBKDF2_ITERATIONS: 50000,
  PASSWORD_HASH_ALGORITHM_PBKDF2_KEY_BYTE_SIZE: 64
};
